---
title: "R Programming Course - Week 2 Programming Assignment"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r Pollutantmean function}

pollutantmean <- function(directory, pollutant, id=1:332) { 
  
  # Create a list of files in the directory argument
  files_list <- list.files(directory, full.names = TRUE) 
  df <- data.frame() #creates an empty data frame
  
  # Loop through the files, rbinding them together
  for (i in id) {
    df <- rbind(df, read.csv(files_list[i]))
  }
  
  # Subset the column that matches the 'pollutant'  argument
  df_subset <- df[,pollutant] 
  
  # Calculate the mean value
  mean(df_subset, na.rm = TRUE) 
}
```

```{r Pollutantmean Test #1}
pollutantmean("specdata", "sulfate", 1:10) 
```
```{r Pollutantmean Test #2}
pollutantmean("specdata", "nitrate", 70:72)
```
```{r Pollutantmean Test #3}
pollutantmean("specdata", "sulfate", 34)
```
```{r Pollutantmean Test #4}
pollutantmean("specdata", "nitrate")
```

```{r Complete Function}
complete <- function(directory,id=1:332) { 
  
  # Create a list of files in the directory argument
  files_list <- list.files(directory, full.names = TRUE)
  df1 <- data.frame() #creates an empty data frame
  
  # Loop through the files, rbinding them together
  for (i in id) {
    df1 <- rbind(df1, read.csv(files_list[i]))
  }
  
  # Filter out the rows where 'NA' shows up in either the sulfate or nitrate columns
  df1 <- df1[ !is.na(df1$sulfate & df1$nitrate), ]
  
  # Initialize the row index of the output dataframe
  running.index <- 0
  
  # Set up the 'container' vectors for 'monitorid' and 'nobs'
  monitorid <- numeric(length(id))
  nobs <- numeric(length(id))
  
  for (i in id) {
    running.index <- running.index+1
    monitorid[running.index] <- i
    nobs[running.index] <- sum(df1$ID == i)
  }
  
  monitorid <- monitorid[1:running.index]
  nobs <- nobs[1:running.index]
  
  # Create a dataframe from the 'monitorid' and 'nobs' vectors.
  result <- data.frame(monitorid,nobs)
}
```

```{r Complete Function Test #1}
RNGversion("3.5.1")  
set.seed(42)
cc <- complete("specdata", 332:1)
use <- sample(332, 10)
print(cc[use, "nobs"])
```

```{r Corr Function}
corr <- function(directory, threshold = 0) {
  
  # Make sure the R data.table package is loaded
  require(data.table)
  
  # Reading in all files and making a large data.table
  files_list <- lapply(file.path(directory, list.files(path = directory,pattern ="*.csv")), data.table::fread)
  
  # Bind all of the csv files together into one big file.
  dt <- rbindlist(files_list)
  
  # Only keep the completely observed cases
  dt <- dt[complete.cases(dt),]
  
  # Apply threshold and calculate correlations for those IDs whose nobs exceed the threshold 
  dt <- dt[, .(nobs = .N, corr = cor(x = sulfate, y = nitrate)), by = ID][nobs > threshold]
  
  return(dt[, corr])
}
```

```{r}
v = corr("specdata",150)
v
```

```{r}
cr <- corr("specdata")                
cr <- sort(cr)   
RNGversion("3.5.1")
set.seed(868)                
out <- round(cr[sample(length(cr), 5)], 4)
print(out)
```
```{r}
cr <- corr("specdata", 129)                
cr <- sort(cr)                
n <- length(cr)    
RNGversion("3.5.1")
set.seed(197)                
out <- c(n, round(cr[sample(n, 5)], 4))
print(out)
```
```{r}
cr <- corr("specdata", 2000)                
n <- length(cr)                
cr <- corr("specdata", 1000)                
cr <- sort(cr)
print(c(n, round(cr, 4)))
```

