---
title: "Week 3 Plotly Assignment"
subtitle: "Developing Data Products in R"
author: "Ken Wood"
date: "9/30/2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format = "html") 
```

```{r echo=FALSE,message=FALSE}
rm(list = ls())
library(plotly)
setwd("~/Desktop/Data Science with R/Developing Data Products/Week 3 Assignment")
housingdata = read.csv("housingdata.csv")
```

```{r echo=FALSE,message=FALSE}
dense <- density(housingdata$saleprice)
```

## Histogram of Housing Prices

```{r echo=FALSE,message=FALSE,warning=FALSE}
# set margins for plots
m <- list(l = 50,r = 50,b = 50,t = 50,pad = 4)

fig1 <- plot_ly(data = housingdata, x = ~saleprice, type = "histogram", name = "Histogram",width = 750, height = 500) %>% add_trace(x = dense$x, y = dense$y, type = "scatter", mode = "lines", fill = "tozeroy", yaxis = "y2",name="Density") %>%  layout(autosize = F,  margin = m) %>% layout(yaxis2 = list(overlaying = "y", side = "right",title = "Density"),title="Histogram & Density of Saleprice") %>% layout(xaxis = list(title="Sale Price ($)")) %>% layout(yaxis = list(side = "left",title = "Number of Instances"),title="Histogram & Density of Saleprice") %>% layout(legend = list(x = 0.7, y = 0.9))
fig1
```

## Box Plot of Saleprice vs. Home Condition

```{r echo=FALSE,message=FALSE,warning=FALSE}
fig2 <- plot_ly(data = housingdata, x = ~overallcond, y = ~saleprice, type = "box",width = 750, height = 400, color=~housingdata$centralair,name=~housingdata$centralair) %>% layout(boxmode = "group") %>% layout(legend = list(x = 0.9, y = 0.9, title=list(text="Has Central Air?")))

fig2 <- fig2 %>% layout(yaxis = list(separators = ".,",title="Sale Price ($)")) %>% layout(xaxis = list(title="Overall Home Condition (1 = Poor 9, = Excellent)"))
fig2
```

## Scatter Plot of Saleprice vs. Lot Area

```{r echo=FALSE,message=FALSE}
fig3 <- plot_ly(data = housingdata, x = ~lotarea, y = ~saleprice, type = "scatter", color=~overallcond) %>% layout(yaxis = list(separators = ".,",title="Sale Price ($)")) %>% layout(xaxis = list(title="Lot Area (SqFt)"))
fig3
```


