---
title: "Week 4 Course Project"
author: "Ken Wood"
date: "7/17/2020"
output:
  pdf_document: default
  html_document: default
---

```{r run_analysis.R}

# Create one R script called run_analysis.R that does the following:

# 1. Merges the training and the test sets to create one data set.
# 2. Extracts only the measurements on the mean and standard deviation for each measurement.
# 3. Uses descriptive activity names to name the activities in the data set
# 4. Appropriately labels the data set with descriptive variable names.
# 5. From the data set in step 4, creates a second, independent tidy data set with the 
#    average of each variable for each activity and each subject.

download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip","dataset.zip")
```

```{r}

# Read in X_train and assign column labels from 'features.txt' file
X_train <- read.table("X_train.txt", col.names=scan('features.txt', what ="", sep = "\t", quiet = TRUE),check.names = FALSE)

# Read in y_train and assign column label "Activity"
y_train <- read.table("y_train.txt",col.names = "Activity")

# Read in subject_train and assign column label "Subject"
subject_train <- read.table("subject_train.txt",col.names = "Subject")

# Read in X_test and assign column labels from 'features.txt' file
X_test <- read.table("X_test.txt", col.names=scan('features.txt', what ="", sep = "\t", quiet = TRUE),check.names = FALSE)

# Read in y_test and assign column label "Activity"
y_test <- read.table("y_test.txt",col.names = "Activity")

# Read in subject_test and assign column label "Subject"
subject_test <- read.table("subject_test.txt",col.names = "Subject")

# Combine X_train and X_test to form df
df <- rbind.data.frame(X_train,X_test)

# Combine y_train and y_test to "Activity" column
activity <- rbind.data.frame(y_train,y_test)

# Combine subject_train and subject_test to "Subject" column
subject <- rbind.data.frame(subject_train,subject_test)
```

```{r}
# Select columns that only contain means and standard deviations.
# The grep pattern is "mean\\(\\)" and "std\\(\\)"

df1 <- df[ , grep("mean\\(\\)", names(df), perl = TRUE ) ]
df2 <- df[ , grep("std\\(\\)", names(df), perl = TRUE ) ]
final_df <- cbind(df1,df2)
final_df <- final_df[,order(names(final_df))]

# Add activity and subject vectors to final_df
final_df <- cbind(activity,subject,final_df)

# Adjust typo for columns with "BodyBody" in their name.
names(final_df) <- gsub("BodyBody", "Body", names(final_df), fixed = TRUE)

# Uncode the activities in the "Activities" column
final_df$Activity[which(final_df$Activity == 1)] ="WALKING"
final_df$Activity[which(final_df$Activity == 2)] ="WALKING_UPSTAIRS"
final_df$Activity[which(final_df$Activity == 3)] ="WALKING_DOWNSTAIRS"
final_df$Activity[which(final_df$Activity == 4)] ="SITTING"
final_df$Activity[which(final_df$Activity == 5)] ="STANDING"
final_df$Activity[which(final_df$Activity == 6)] ="LAYING"

```

```{r}
# Now, we generate the script to create a tidy dataset

library(plyr)
library(dplyr)

# Sort final_df by Activity and Subject
final_df <- final_df[order(final_df$Subject, final_df$Activity),]
means <- suppressWarnings(aggregate(final_df,by = list(final_df$Activity,final_df$Subject),function (x) mean(as.numeric(as.character(x)))))
means <- subset(means, select=-c(Activity,Subject))
names(means)[names(means)=="Group.1"] <- "Activity"
names(means)[names(means)=="Group.2"] <- "Subject"
means <- means %>% select(Subject, everything())
```




